Repository huggingface/setfit, pull requests merged in 2022-12, with the labels that each got.

#233 Expand CI tests using matrix; make dependencies less restrictive; fix ONNX tests
  .github/workflows/tests.yml
  setup.py
  src/setfit/exporters/onnx.py
  tests/exporters/test_onnx.py
Labels: enhancement, CI

#229 Add SetFitModel.to
  src/setfit/modeling.py
  tests/test_modeling.py
Labels: enhancement

#235 Prevent the CI from reusing old cached versions of `setfit`
  .github/workflows/tests.yml
Labels: bug, CI

#231 Prevent overriding the sample size in `sample_dataset`
  src/setfit/data.py
  tests/test_data.py
Labels: bug

#239 add related work in readme
  README.md
Labels: documentation

#240 Always display test coverage; add tests
  .coveragerc
  setup.cfg
  tests/exporters/test_onnx.py
  tests/test_data.py
Labels: CI, tests
