Repository huggingface/setfit, pull requests merged in 2023-01, with the labels that each got.

#214 Added support of OpenVINO export
  notebooks/openvino_inference.ipynb
  setup.py
  src/setfit/exporters/onnx.py
  src/setfit/exporters/openvino.py
  tests/exporters/test_openvino.py
Labels: enhancement, exporting

#207 Allow passing numpy.ndarray to SetFitHead.predict_proba
  src/setfit/modeling.py
Labels: bug

#203 Feature/deprecate binary cross entropy loss
  src/setfit/modeling.py
  tests/test_modeling.py
Labels: bug

#277 Fix Auth Token Bug
  src/setfit/modeling.py
Labels: bug

#272 Feature/setfithead multi target
  README.md
  src/setfit/data.py
  src/setfit/modeling.py
  tests/test_modeling.py
  tests/test_trainer.py
Labels: enhancement

#262 Automatically create summary table after `scripts/setfit/run_fewshot.py`
  scripts/create_summary_table.py
  scripts/setfit/run_fewshot.py
Labels: enhancement

#280 Fix squared optimization steps bug
  src/setfit/trainer.py
Labels: bug

#284 Fix squared optimization steps bug in distillation trainer
  src/setfit/trainer_distillation.py
Labels: bug

#288 Dynamic features in datasets based on model input names
  src/setfit/data.py
  src/setfit/modeling.py
  tests/test_data.py
Labels: enhancement
