Repository huggingface/setfit, pull requests merged in 2023-07, with the labels that each got.

#401 Restrict hummingbird-lm to `<0.4.9` to resolve CI issues
  setup.py
Labels: CI

#361 Remove coef_ requirement from ONNX exporter.
  src/setfit/exporters/onnx.py
  tests/exporters/test_onnx.py
Labels: enhancement, exporting

#396 Update data.py
  src/setfit/data.py
  tests/test_data.py
Labels: enhancement

#402 Allow other datasets in `trainer.evaluate()`
  src/setfit/trainer.py
  tests/test_trainer.py
Labels: enhancement

#363 Normalize device to CPU when evaluating
  src/setfit/trainer.py
  tests/test_trainer.py
Labels: enhancement
