Repository huggingface/setfit, pull requests merged in 2023-04, with the labels that each got.

#350 Restrict `pandas` to <2 for compatibility tests
  Makefile
  setup.py
Labels: CI, tests

#351 Update `Trainer.push_to_hub` to use `**kwargs`
  src/setfit/modeling.py
  src/setfit/trainer.py
Labels: bug, enhancement, refactor

#353 Add metric keyword arguments, e.g. add "average" strategy to f1
  src/setfit/trainer.py
  tests/test_trainer.py
Labels: enhancement

#366 Fix docstring
  src/setfit/modeling.py
Labels: documentation
