Repository huggingface/setfit, pull requests merged in 2023-02, with the labels that each got.

#283 Resolve `SentenceTransformer` resetting devices after moving a `SetFitModel`
  src/setfit/modeling.py
  tests/test_modeling.py
Labels: bug

#302 Updated zeroshot code in `README.md`
  README.md
Labels: documentation

#286 Exclude compatibility versions from `.[dev]` install
  setup.py
Labels: bug, admin, installation

#299 Add a warning if an unsplit dataset is passed to SetFitTrainer
  src/setfit/trainer.py
  tests/test_trainer.py
Labels: enhancement

#312 Add cache for 🤗 Hub models in the CI
  .github/workflows/tests.yml
Labels: enhancement, CI, admin

#321 Fix output of hyperparameter search notebook
  notebooks/text-classification_hyperparameter-search.ipynb
Labels: documentation
